### PR TITLE
Move to SecKeyCreateRandomKey from SecKeyGeneratePair

### PR DESCRIPTION
**Pull request by feralbob**
SecKeyGeneratePair is deprecated as of iOS 15

### CODE REVIEW

**Comment by feralbob** [comment]
Note sure what if anything I need to do to prevent this error stalling the checks

> ERROR: Project not found. Please check the 'sonar.projectKey' and 'sonar.organization' properties, the 'SONAR_TOKEN' environment variable, or contact the project administrator

**Comment by kdubb** [comment]
That's an issue with SonarCloud I'll need to fix... apparently it doesn't work with PR's from external branches

**Comment by kdubb** [comment]
@feralbob Can you rebase your PR branch with `main` and repush. It should skip the sonar scanner now.

**Comment by feralbob** [comment]
@kdubb Hrmmm... I think this got caught in yesterdays [outage](https://www.githubstatus.com/incidents/t2xwk9mz56f4) - is there a way to trigger the CI without pushing to my PR branch again?

**Comment by kdubb** [comment]
I'm working on the workflows to support external PR's properly. I'll let you know when it's ready. It'll need a rebase again to work.

**Comment by kdubb** [comment]
@feralbob Are both the public and private key added to the keychain (in all cases e.g. SecureEnclave) and all platforms by using `kSecAttrIsPermanent`?

The following code is basically to ensure that the above happens the same for all platforms:
```swift
#if os(iOS) || os(watchOS) || os(tvOS)

  if !flags.contains(.secureEnclave) {
    try privateKey!.save()
  }

  try publicKey!.save()

#elseif os(macOS)

  if flags.contains(.secureEnclave) {
    try publicKey!.save()
  }

#endif
```

This is an example of bad documentation because this is not spelled out in anywhere but it is required behavior.

**Comment by kdubb** [comment]
It appears the above requirements are not tested either 😏

**Comment by feralbob** [comment]
I believe that the `kSecAttrIsPermanent` does store the private key in the keychain for all platforms... 

Without that the tests fails
```
Failing tests:
	SecKeyPairTests.testCodable()
	SecKeyPairTests.testGenerateSecureEnclave()
	SecKeyPairTests.testImportExport()
	SecKeyPairTests.testPersistentLoadEC()
	SecKeyPairTests.testPersistentLoadRSA()

** TEST FAILED **
```

With the error 

```testPersistentLoadRSA(): failed: caught error: "Error Domain=(extension in ShieldSecurity):__C.SecKeyRef.Error Code=0 "Unable to locate transient reference" UserInfo={NSLocalizedDescription=Unable to locate transient reference, status=-25300}"```

`-253000` corresponds to `errSecItemNotFound`

It could be possible that the public key isn't stored in the keychain by default. I'll double check that later tonight. But it might be possible to make that stored by supplying the attributes for both public/private in a dictionary.

```The values below may be set either in the top-level dictionary or in a
 dictionary that is the value of the kSecPrivateKeyAttrs or
 kSecPublicKeyAttrs key in the top-level dictionary.  Setting these
 attributes explicitly will override the defaults below.  See SecItem.h
 for detailed information on these attributes including the types of
 the values.

 * kSecAttrLabel default NULL
 * kSecAttrIsPermanent if this key is present and has a Boolean value of true,
   the key or key pair will be added to the default keychain.
```

I'll try and poke around in the simulator keychain to see what is actually added during the execution.

**Comment by kdubb** [comment]
Awesome! Awaiting update.

I'll push an added DocC comment to this method including these expectations.

**Comment by kdubb** [comment]
I've added tests and checked the previous functionality. I believe it works as expected.

**Comment by kdubb** [comment]
Thanks for the update!

**Comment by feralbob** [comment]
Thanks @kdubb - I did start to double check - but got distracted with regular work and 🤢 kids.
In my investigation, I concur that it looks like things are stored in the Keychain correctly - I'll take a look at your tests.

Thanks for your help and answering my dumb questions the other weekend :)

**Pull request merged**
