### PR TITLE
Use modern APIs for signatures

### PR DESCRIPTION
**Pull request by mjg59**
The older APIs currently used for signing don't support the use of hardware-backed keys. Here we simply replace them with the modern SecKey signature API.

### CODE REVIEW

**Comment by kdubb** [comment]
I'm assuming these are cryptographically equivalent?

**Comment by mjg59** [comment]
in theory, yes. I initially implemented signHash and left verifyHash unmodified - all tests still passed, which implies that this is true.

**Comment by j0h4nn3s** [comment]
+1 for this change. Any updates?

**Comment by kdubb** [comment]
I agree with the update, I just need to verify @mjg59 is correct and that these are swappable for all ranges of input. I'll get this done in the next couple days.

**Comment by mjg59** [comment]
@kdubb Thanks, and thanks for also doing the encrypt/decrypt side of things!

**Pull request merged**
